import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import QRCode from 'qrcode';
import { AnalyticsData, InstagramAccount, ExportOptions } from '@/types/analytics';

export interface ChartData {
  id: string;
  name: string;
  data: any[];
  type: 'line' | 'bar' | 'area' | 'pie';
  title: string;
}

export interface ExportData {
  accounts: InstagramAccount[];
  charts: ChartData[];
  analyticsData: AnalyticsData;
  timeRange: {
    start: Date;
    end: Date;
  };
  generatedAt: Date;
}

// PDF Export Utilities
export const generatePDFReport = async (data: ExportData, options: {
  title?: string;
  includeCharts?: boolean;
  includeAnalytics?: boolean;
  template?: 'executive' | 'detailed' | 'custom';
}): Promise<Blob> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(147, 51, 234); // Purple color
  pdf.text(options.title || 'Instagram Analytics Report', margin, yPosition);
  yPosition += 15;

  // Date range
  pdf.setFontSize(12);
  pdf.setTextColor(100, 100, 100);
  const dateRange = `${data.timeRange.start.toLocaleDateString()} - ${data.timeRange.end.toLocaleDateString()}`;
  pdf.text(`Report Period: ${dateRange}`, margin, yPosition);
  yPosition += 10;
  
  pdf.text(`Generated: ${data.generatedAt.toLocaleDateString()}`, margin, yPosition);
  yPosition += 20;

  // Executive Summary
  if (options.template !== 'detailed') {
    pdf.setFontSize(18);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Executive Summary', margin, yPosition);
    yPosition += 15;

    pdf.setFontSize(12);
    const summary = generateExecutiveSummary(data);
    const splitSummary = pdf.splitTextToSize(summary, pageWidth - 2 * margin);
    pdf.text(splitSummary, margin, yPosition);
    yPosition += splitSummary.length * 5 + 15;
  }

  // Analytics Overview
  if (options.includeAnalytics !== false) {
    pdf.setFontSize(18);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Analytics Overview', margin, yPosition);
    yPosition += 15;

    // Key metrics
    const metrics = [
      { label: 'Total Followers', value: data.analyticsData.followers.toLocaleString() },
      { label: 'Engagement Rate', value: `${data.analyticsData.engagementRate.toFixed(2)}%` },
      { label: 'Total Reach', value: data.analyticsData.reach.toLocaleString() },
      { label: 'Total Likes', value: data.analyticsData.likes.toLocaleString() },
      { label: 'Total Comments', value: data.analyticsData.comments.toLocaleString() }
    ];

    metrics.forEach((metric) => {
      pdf.setFontSize(12);
      pdf.setTextColor(0, 0, 0);
      pdf.text(`${metric.label}:`, margin, yPosition);
      pdf.setTextColor(147, 51, 234);
      pdf.text(metric.value, margin + 60, yPosition);
      yPosition += 8;
    });

    yPosition += 10;

    // Growth metrics
    pdf.setFontSize(14);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Growth Metrics', margin, yPosition);
    yPosition += 10;

    const growthMetrics = [
      { label: 'Follower Growth', value: `${data.analyticsData.growth.followers.toFixed(1)}%` },
      { label: 'Engagement Growth', value: `${data.analyticsData.growth.engagement.toFixed(1)}%` },
      { label: 'Reach Growth', value: `${data.analyticsData.growth.reach.toFixed(1)}%` }
    ];

    growthMetrics.forEach((metric) => {
      pdf.setFontSize(12);
      pdf.setTextColor(0, 0, 0);
      pdf.text(`${metric.label}:`, margin, yPosition);
      pdf.setTextColor(34, 197, 94); // Green for growth
      pdf.text(metric.value, margin + 60, yPosition);
      yPosition += 8;
    });

    yPosition += 20;
  }

  // Charts
  if (options.includeCharts !== false && data.charts.length > 0) {
    for (let i = 0; i < data.charts.length; i++) {
      const chart = data.charts[i];
      
      // Check if we need a new page
      if (yPosition > pageHeight - 60) {
        pdf.addPage();
        yPosition = margin;
      }

      pdf.setFontSize(16);
      pdf.setTextColor(0, 0, 0);
      pdf.text(chart.title, margin, yPosition);
      yPosition += 10;

      // Add chart image (placeholder for now - would need chart DOM element)
      pdf.setFillColor(248, 250, 252);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 40, 'F');
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text('[Chart Image Placeholder]', margin + 10, yPosition + 25);
      yPosition += 50;
    }
  }

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  const footerText = 'Generated by Instagram GrowthHub Analytics';
  pdf.text(footerText, margin, pageHeight - 10);

  return new Blob([pdf.output('blob')], { type: 'application/pdf' });
};

export const downloadPDF = async (data: ExportData, options: any = {}) => {
  try {
    const pdfBlob = await generatePDFReport(data, options);
    const fileName = `instagram-analytics-${new Date().toISOString().split('T')[0]}.pdf`;
    saveAs(pdfBlob, fileName);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

// CSV/Excel Export
export const exportToCSV = (data: ExportData, filename?: string) => {
  // Convert analytics data to CSV format
  const csvData = [
    ['Metric', 'Value', 'Previous Period', 'Growth %'],
    ['Total Followers', data.analyticsData.followers, '', ''],
    ['Engagement Rate', `${data.analyticsData.engagementRate}%`, '', ''],
    ['Total Reach', data.analyticsData.reach, '', ''],
    ['Total Likes', data.analyticsData.likes, '', ''],
    ['Total Comments', data.analyticsData.comments, '', ''],
    ['Follower Growth', `${data.analyticsData.growth.followers}%`, '', ''],
    ['Engagement Growth', `${data.analyticsData.growth.engagement}%`, '', ''],
    ['Reach Growth', `${data.analyticsData.growth.reach}%`, '', '']
  ];

  const csvContent = csvData.map(row => row.join(',')).join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const fileName = filename || `analytics-data-${new Date().toISOString().split('T')[0]}.csv`;
  saveAs(blob, fileName);
};

export const exportToExcel = (data: ExportData, filename?: string) => {
  const workbook = XLSX.utils.book_new();

  // Summary sheet
  const summaryData = [
    ['Instagram Analytics Summary'],
    ['Report Period', `${data.timeRange.start.toLocaleDateString()} - ${data.timeRange.end.toLocaleDateString()}`],
    ['Generated At', data.generatedAt.toLocaleString()],
    [''],
    ['Key Metrics'],
    ['Total Followers', data.analyticsData.followers],
    ['Engagement Rate', `${data.analyticsData.engagementRate.toFixed(2)}%`],
    ['Total Reach', data.analyticsData.reach],
    ['Total Likes', data.analyticsData.likes],
    ['Total Comments', data.analyticsData.comments],
    [''],
    ['Growth Metrics'],
    ['Follower Growth', `${data.analyticsData.growth.followers.toFixed(1)}%`],
    ['Engagement Growth', `${data.analyticsData.growth.engagement.toFixed(1)}%`],
    ['Reach Growth', `${data.analyticsData.growth.reach.toFixed(1)}%`]
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Chart data sheets
  data.charts.forEach((chart, index) => {
    const chartSheet = XLSX.utils.json_to_sheet(chart.data);
    XLSX.utils.book_append_sheet(workbook, chartSheet, chart.name.substring(0, 31));
  });

  // Accounts sheet
  const accountsData = data.accounts.map(account => ({
    Username: account.username,
    'Display Name': account.display_name,
    'Followers': account.follower_count,
    'Following': account.following_count,
    'Media Count': account.media_count,
    'Is Business': account.is_business ? 'Yes' : 'No'
  }));
  const accountsSheet = XLSX.utils.json_to_sheet(accountsData);
  XLSX.utils.book_append_sheet(workbook, accountsSheet, 'Accounts');

  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const excelBlob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const fileName = filename || `instagram-analytics-${new Date().toISOString().split('T')[0]}.xlsx`;
  saveAs(excelBlob, fileName);
};

// JSON Export
export const exportToJSON = (data: ExportData, filename?: string) => {
  const jsonData = {
    metadata: {
      reportType: 'instagram-analytics',
      generatedAt: data.generatedAt.toISOString(),
      timeRange: {
        start: data.timeRange.start.toISOString(),
        end: data.timeRange.end.toISOString()
      }
    },
    accounts: data.accounts,
    analytics: data.analyticsData,
    charts: data.charts.map(chart => ({
      id: chart.id,
      name: chart.name,
      type: chart.type,
      data: chart.data
    }))
  };

  const jsonBlob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
  const fileName = filename || `analytics-data-${new Date().toISOString().split('T')[0]}.json`;
  saveAs(jsonBlob, fileName);
};

// Chart Image Export
export const exportChartAsImage = async (chartElementId: string, format: 'png' | 'jpeg' = 'png') => {
  const element = document.getElementById(chartElementId);
  if (!element) {
    throw new Error(`Chart element with id ${chartElementId} not found`);
  }

  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: '#ffffff',
    logging: false
  });

  return new Promise<Blob>((resolve) => {
    canvas.toBlob((blob) => {
      resolve(blob!);
    }, `image/${format}`, 0.9);
  });
};

export const downloadChartImage = async (chartElementId: string, filename?: string, format: 'png' | 'jpeg' = 'png') => {
  try {
    const blob = await exportChartAsImage(chartElementId, format);
    const fileName = filename || `chart-${chartElementId}-${new Date().toISOString().split('T')[0]}.${format}`;
    saveAs(blob, fileName);
  } catch (error) {
    console.error('Error exporting chart:', error);
    throw error;
  }
};

// Batch Export
export const performBatchExport = async (data: ExportData[], options: {
  formats: ('pdf' | 'csv' | 'excel' | 'json')[];
  includeCharts?: boolean;
}) => {
  const results = [];

  for (const exportData of data) {
    const exports = [];
    
    for (const format of options.formats) {
      try {
        switch (format) {
          case 'pdf':
            const pdfBlob = await generatePDFReport(exportData, {
              includeCharts: options.includeCharts
            });
            exports.push({ format, blob: pdfBlob, filename: `report-${exportData.timeRange.start.toISOString().split('T')[0]}.pdf` });
            break;
          case 'csv':
            // CSV export logic here
            exports.push({ format, blob: null, filename: `data-${exportData.timeRange.start.toISOString().split('T')[0]}.csv` });
            break;
          case 'excel':
            // Excel export logic here
            exports.push({ format, blob: null, filename: `data-${exportData.timeRange.start.toISOString().split('T')[0]}.xlsx` });
            break;
          case 'json':
            // JSON export logic here
            exports.push({ format, blob: null, filename: `data-${exportData.timeRange.start.toISOString().split('T')[0]}.json` });
            break;
        }
      } catch (error) {
        console.error(`Error exporting ${format}:`, error);
      }
    }
    
    results.push({ exports });
  }

  return results;
};

// QR Code Generation
export const generateQRCode = async (data: string, options?: {
  size?: number;
  margin?: number;
}): Promise<string> => {
  try {
    const qrDataURL = await QRCode.toDataURL(data, {
      width: options?.size || 256,
      margin: options?.margin || 2,
      color: {
        dark: '#000000',
        light: '#FFFFFF'
      }
    });
    return qrDataURL;
  } catch (error) {
    console.error('Error generating QR code:', error);
    throw error;
  }
};

// Shareable Link Generation
export const generateShareableLink = (data: {
  reportId: string;
  timeRange: string;
  filters?: Record<string, any>;
}): string => {
  const baseUrl = window.location.origin;
  const params = new URLSearchParams({
    report: data.reportId,
    period: data.timeRange,
    ...data.filters
  });
  
  return `${baseUrl}/shared-report?${params.toString()}`;
};

// Helper Functions
const generateExecutiveSummary = (data: ExportData): string => {
  const followerGrowth = data.analyticsData.growth.followers;
  const engagementGrowth = data.analyticsData.growth.engagement;
  
  let summary = `Your Instagram analytics report for ${data.accounts.length} account(s) shows `;
  
  if (followerGrowth > 0) {
    summary += `positive growth with ${followerGrowth.toFixed(1)}% increase in followers. `;
  } else {
    summary += `a decline of ${Math.abs(followerGrowth).toFixed(1)}% in followers. `;
  }
  
  if (engagementGrowth > 0) {
    summary += `Engagement rates improved by ${engagementGrowth.toFixed(1)}% during this period. `;
  } else {
    summary += `Engagement rates decreased by ${Math.abs(engagementGrowth).toFixed(1)}% during this period. `;
  }
  
  summary += `Total reach of ${data.analyticsData.reach.toLocaleString()} with ${data.analyticsData.likes.toLocaleString()} likes and ${data.analyticsData.comments.toLocaleString()} comments.`;
  
  return summary;
};

// Mock data generator for testing
export const generateMockExportData = (): ExportData => {
  return {
    accounts: [
      {
        id: '1',
        username: 'test_account',
        display_name: 'Test Account',
        follower_count: 15000,
        following_count: 500,
        media_count: 250,
        is_business: true,
        created_at: '2023-01-01',
        updated_at: new Date().toISOString()
      }
    ],
    charts: [
      {
        id: 'follower-growth',
        name: 'Follower Growth',
        type: 'line',
        title: 'Follower Growth Over Time',
        data: generateMockChartData(30)
      },
      {
        id: 'engagement-trend',
        name: 'Engagement Trend',
        type: 'line',
        title: 'Engagement Rate Trends',
        data: generateMockChartData(30)
      }
    ],
    analyticsData: {
      followers: 15000,
      engagementRate: 4.2,
      reach: 250000,
      likes: 12500,
      comments: 890,
      growth: {
        followers: 15.3,
        engagement: 8.7,
        reach: 22.1,
        likes: 18.4,
        comments: 12.9
      },
      period: {
        start: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        end: new Date()
      }
    },
    timeRange: {
      start: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      end: new Date()
    },
    generatedAt: new Date()
  };
};

const generateMockChartData = (days: number): any[] => {
  const data = [];
  const baseValue = 100;
  
  for (let i = 0; i < days; i++) {
    const date = new Date(Date.now() - (days - i) * 24 * 60 * 60 * 1000);
    data.push({
      date: date.toISOString().split('T')[0],
      value: baseValue + Math.random() * 50 + (i * 2),
      name: date.toLocaleDateString()
    });
  }
  
  return data;
};