CREATE TABLE account_audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    instagram_account_id UUID NOT NULL,
    audit_date DATE DEFAULT CURRENT_DATE,
    overall_score INTEGER,
    profile_optimization_score INTEGER,
    content_quality_score INTEGER,
    engagement_score INTEGER,
    growth_score INTEGER,
    hashtag_strategy_score INTEGER,
    posting_schedule_score INTEGER,
    visual_quality_score INTEGER,
    audit_results JSONB,
    optimization_suggestions JSONB,
    improvement_priorities JSONB,
    competitor_comparison JSONB,
    strengths TEXT[],
    weaknesses TEXT[],
    opportunities TEXT[],
    threats TEXT[],
    action_items JSONB,
    estimated_impact JSONB,
    implementation_difficulty VARCHAR(20),
    next_audit_date DATE,
    is_latest BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW()
);