CREATE TABLE ai_intelligent_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    account_id UUID REFERENCES instagram_accounts(id) ON DELETE CASCADE,
    report_type VARCHAR(50) NOT NULL,
    report_title VARCHAR(255) NOT NULL,
    report_period_start DATE NOT NULL,
    report_period_end DATE NOT NULL,
    executive_summary TEXT,
    key_insights JSONB,
    performance_metrics JSONB,
    growth_analysis JSONB,
    content_analysis JSONB,
    audience_insights JSONB,
    recommendations JSONB,
    strengths JSONB,
    weaknesses JSONB,
    opportunities JSONB,
    threats JSONB,
    action_items JSONB,
    overall_score INTEGER,
    report_data JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);