CREATE TABLE competitor_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_account_id UUID NOT NULL,
    user_id UUID NOT NULL,
    metric_date DATE NOT NULL,
    followers_count INTEGER,
    following_count INTEGER,
    posts_count INTEGER,
    engagement_rate DECIMAL(5,2),
    avg_likes DECIMAL(10,2),
    avg_comments DECIMAL(10,2),
    stories_count INTEGER,
    reels_count INTEGER,
    top_hashtags JSONB,
    top_post_id VARCHAR(255),
    top_post_likes INTEGER,
    top_post_comments INTEGER,
    posting_times JSONB,
    content_types JSONB,
    follower_growth INTEGER,
    engagement_growth DECIMAL(5,2),
    benchmark_score INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);