CREATE TABLE competitor_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    instagram_account_id UUID NOT NULL,
    competitor_username VARCHAR(255) NOT NULL,
    competitor_user_id VARCHAR(255),
    display_name VARCHAR(255),
    profile_pic_url TEXT,
    bio TEXT,
    followers_count INTEGER,
    following_count INTEGER,
    posts_count INTEGER,
    engagement_rate DECIMAL(5,2),
    avg_likes DECIMAL(10,2),
    avg_comments DECIMAL(10,2),
    posting_frequency DECIMAL(5,2),
    category VARCHAR(100),
    is_verified BOOLEAN DEFAULT false,
    is_business BOOLEAN DEFAULT false,
    website_url TEXT,
    email VARCHAR(255),
    phone VARCHAR(50),
    tracking_enabled BOOLEAN DEFAULT true,
    notes TEXT,
    added_at TIMESTAMP DEFAULT NOW(),
    last_updated TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);