CREATE TABLE hashtag_monitoring (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    instagram_account_id UUID NOT NULL,
    hashtag VARCHAR(255) NOT NULL,
    hashtag_clean VARCHAR(255) NOT NULL,
    posts_count INTEGER,
    trend_score INTEGER,
    volume_tier VARCHAR(20),
    competition_level VARCHAR(20),
    engagement_rate DECIMAL(5,2),
    reach_potential INTEGER,
    growth_rate DECIMAL(5,2),
    is_trending BOOLEAN DEFAULT false,
    trend_start_date DATE,
    peak_date DATE,
    seasonal_pattern JSONB,
    related_hashtags JSONB,
    top_posts JSONB,
    competitor_usage JSONB,
    recommendation_score INTEGER,
    usage_frequency INTEGER DEFAULT 0,
    last_used_date TIMESTAMP,
    performance_metrics JSONB,
    tracking_enabled BOOLEAN DEFAULT true,
    added_at TIMESTAMP DEFAULT NOW(),
    last_updated TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);