CREATE TABLE influencer_database (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    instagram_account_id UUID NOT NULL,
    username VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    profile_pic_url TEXT,
    bio TEXT,
    followers_count INTEGER,
    following_count INTEGER,
    posts_count INTEGER,
    engagement_rate DECIMAL(5,2),
    avg_likes DECIMAL(10,2),
    avg_comments DECIMAL(10,2),
    niche VARCHAR(100),
    content_categories JSONB,
    audience_demographics JSONB,
    is_verified BOOLEAN DEFAULT false,
    collaboration_status VARCHAR(50) DEFAULT 'discovered',
    collaboration_history JSONB,
    outreach_attempts INTEGER DEFAULT 0,
    last_outreach_date TIMESTAMP,
    response_status VARCHAR(50),
    collaboration_roi DECIMAL(10,2),
    influencer_score INTEGER,
    relevance_score INTEGER,
    quality_score INTEGER,
    notes TEXT,
    added_at TIMESTAMP DEFAULT NOW(),
    last_updated TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);