CREATE TABLE market_research_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    instagram_account_id UUID NOT NULL,
    insight_type VARCHAR(50) NOT NULL,
    insight_category VARCHAR(100),
    title VARCHAR(500),
    description TEXT,
    trend_data JSONB,
    content_gap_data JSONB,
    audience_insights JSONB,
    industry_benchmarks JSONB,
    seasonal_patterns JSONB,
    forecast_data JSONB,
    confidence_score INTEGER,
    data_sources JSONB,
    actionable_recommendations TEXT[],
    priority_level VARCHAR(20),
    impact_score INTEGER,
    research_date DATE DEFAULT CURRENT_DATE,
    valid_until DATE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW()
);