import React, { useRef } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { FileText, Download, Eye, Settings } from 'lucide-react';

interface PDFReportGeneratorProps {
  data: any;
  options?: {
    title?: string;
    subtitle?: string;
    includeCharts?: boolean;
    includeAnalytics?: boolean;
    template?: 'executive' | 'detailed' | 'custom' | 'presentation';
    showTableOfContents?: boolean;
    includeBranding?: boolean;
    customColors?: {
      primary: string;
      secondary: string;
      accent: string;
    };
  };
  onGenerate?: (pdf: jsPDF) => void;
}

export default function PDFReportGenerator({ data, options = {}, onGenerate }: PDFReportGeneratorProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [showPreview, setShowPreview] = React.useState(false);

  const defaultOptions = {
    title: 'Instagram Analytics Report',
    subtitle: 'Comprehensive Performance Analysis',
    includeCharts: true,
    includeAnalytics: true,
    template: 'executive' as const,
    showTableOfContents: false,
    includeBranding: true,
    customColors: {
      primary: '#9333ea', // Purple
      secondary: '#ec4899', // Pink
      accent: '#06b6d4' // Cyan
    },
    ...options
  };

  const generatePDF = async () => {
    if (!reportRef.current) return;

    setIsGenerating(true);
    try {
      // Create PDF instance
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      let yPosition = margin;

      // Generate report sections
      await generateCoverPage(pdf, yPosition, pageWidth, pageHeight, margin);
      yPosition = await generateExecutiveSummary(pdf, yPosition + 40, pageWidth, margin, defaultOptions);
      yPosition = await generateKeyMetrics(pdf, yPosition + 20, pageWidth, margin, data, defaultOptions);
      
      if (defaultOptions.includeCharts) {
        yPosition = await generateChartsSection(pdf, yPosition + 20, pageWidth, pageHeight, margin, data);
      }
      
      if (defaultOptions.includeAnalytics) {
        yPosition = await generateDetailedAnalytics(pdf, yPosition + 20, pageWidth, margin, data);
      }
      
      await generateFooter(pdf, pageHeight, margin);

      // Call onGenerate callback
      if (onGenerate) {
        onGenerate(pdf);
      }

      // Download the PDF
      const filename = `${defaultOptions.title.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(filename);

    } catch (error) {
      console.error('PDF generation failed:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const generateCoverPage = async (pdf: jsPDF, yPosition: number, pageWidth: number, pageHeight: number, margin: number) => {
    // Background gradient (simplified)
    pdf.setFillColor(245, 245, 255);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');

    // Main title
    pdf.setFontSize(28);
    pdf.setTextColor(147, 51, 234);
    pdf.text(defaultOptions.title, margin, yPosition + 40, { align: 'left' });

    // Subtitle
    pdf.setFontSize(16);
    pdf.setTextColor(100, 100, 100);
    pdf.text(defaultOptions.subtitle, margin, yPosition + 55, { align: 'left' });

    // Date range
    pdf.setFontSize(12);
    pdf.setTextColor(80, 80, 80);
    const dateRange = data?.timeRange ? 
      `${new Date(data.timeRange.start).toLocaleDateString()} - ${new Date(data.timeRange.end).toLocaleDateString()}` :
      new Date().toLocaleDateString();
    pdf.text(`Report Period: ${dateRange}`, margin, yPosition + 75, { align: 'left' });

    // Generated date
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPosition + 90, { align: 'left' });

    // Branding
    if (defaultOptions.includeBranding) {
      pdf.setFontSize(10);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Instagram GrowthHub Analytics', margin, pageHeight - 20, { align: 'left' });
    }

    pdf.addPage();
  };

  const generateExecutiveSummary = async (pdf: jsPDF, yPosition: number, pageWidth: number, margin: number, options: any) => {
    // Check if we need a new page
    if (yPosition > pdf.internal.pageSize.getHeight() - 60) {
      pdf.addPage();
      yPosition = margin;
    }

    // Section header
    pdf.setFontSize(20);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Executive Summary', margin, yPosition);
    yPosition += 15;

    // Generate executive summary content
    const summary = generateExecutiveSummaryContent(data);
    pdf.setFontSize(11);
    pdf.setTextColor(60, 60, 60);
    
    const splitSummary = pdf.splitTextToSize(summary, pageWidth - 2 * margin);
    pdf.text(splitSummary, margin, yPosition);
    
    return yPosition + splitSummary.length * 5 + 20;
  };

  const generateKeyMetrics = async (pdf: jsPDF, yPosition: number, pageWidth: number, margin: number, data: any, options: any) => {
    if (yPosition > pdf.internal.pageSize.getHeight() - 80) {
      pdf.addPage();
      yPosition = margin;
    }

    // Section header
    pdf.setFontSize(18);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Key Performance Metrics', margin, yPosition);
    yPosition += 15;

    // Metrics grid
    const metrics = [
      { 
        label: 'Total Followers', 
        value: data?.analyticsData?.followers?.toLocaleString() || 'N/A',
        color: [59, 130, 246] // Blue
      },
      { 
        label: 'Engagement Rate', 
        value: `${data?.analyticsData?.engagementRate?.toFixed(2) || '0.00'}%`,
        color: [16, 185, 129] // Green
      },
      { 
        label: 'Total Reach', 
        value: data?.analyticsData?.reach?.toLocaleString() || 'N/A',
        color: [139, 92, 246] // Purple
      },
      { 
        label: 'Total Likes', 
        value: data?.analyticsData?.likes?.toLocaleString() || 'N/A',
        color: [236, 72, 153] // Pink
      },
      { 
        label: 'Total Comments', 
        value: data?.analyticsData?.comments?.toLocaleString() || 'N/A',
        color: [245, 158, 11] // Amber
      }
    ];

    const metricWidth = (pageWidth - 2 * margin - 20) / 2; // 2 columns
    const metricHeight = 25;

    metrics.forEach((metric, index) => {
      const col = index % 2;
      const row = Math.floor(index / 2);
      const x = margin + col * (metricWidth + 20);
      const y = yPosition + row * (metricHeight + 10);

      // Metric box
      pdf.setFillColor(...metric.color, 0.1);
      pdf.setDrawColor(...metric.color);
      pdf.rect(x, y, metricWidth, metricHeight, 'FD');

      // Metric label
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text(metric.label, x + 5, y + 8);

      // Metric value
      pdf.setFontSize(16);
      pdf.setTextColor(...metric.color);
      pdf.text(metric.value, x + 5, y + 18);
    });

    return yPosition + Math.ceil(metrics.length / 2) * (metricHeight + 10) + 20;
  };

  const generateChartsSection = async (pdf: jsPDF, yPosition: number, pageWidth: number, pageHeight: number, margin: number, data: any) => {
    // Section header
    pdf.setFontSize(18);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Data Visualizations', margin, yPosition);
    yPosition += 15;

    // Generate chart placeholders
    const charts = [
      { name: 'Follower Growth Trend', type: 'line' },
      { name: 'Engagement Rate Analysis', type: 'area' },
      { name: 'Content Performance', type: 'bar' },
      { name: 'Audience Demographics', type: 'pie' }
    ];

    for (const chart of charts) {
      if (yPosition > pageHeight - 80) {
        pdf.addPage();
        yPosition = margin;
      }

      // Chart title
      pdf.setFontSize(14);
      pdf.setTextColor(0, 0, 0);
      pdf.text(chart.name, margin, yPosition);
      yPosition += 10;

      // Chart placeholder
      pdf.setFillColor(248, 250, 252);
      pdf.setDrawColor(229, 231, 235);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 40, 'FD');

      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`[${chart.type.toUpperCase()} Chart: ${chart.name}]`, margin + 10, yPosition + 25);

      // Add instruction for actual chart generation
      pdf.setFontSize(8);
      pdf.setTextColor(156, 163, 175);
      pdf.text('Replace this placeholder with actual chart image', margin + 10, yPosition + 35);

      yPosition += 50;
    }

    return yPosition + 10;
  };

  const generateDetailedAnalytics = async (pdf: jsPDF, yPosition: number, pageWidth: number, margin: number, data: any) => {
    if (yPosition > pdf.internal.pageSize.getHeight() - 60) {
      pdf.addPage();
      yPosition = margin;
    }

    // Section header
    pdf.setFontSize(18);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Detailed Analytics', margin, yPosition);
    yPosition += 15;

    // Growth metrics table
    const growthMetrics = [
      ['Metric', 'Current Period', 'Growth %'],
      ['Followers', data?.analyticsData?.followers?.toLocaleString() || 'N/A', `${data?.analyticsData?.growth?.followers?.toFixed(1) || '0.0'}%`],
      ['Engagement Rate', `${data?.analyticsData?.engagementRate?.toFixed(2) || '0.00'}%`, `${data?.analyticsData?.growth?.engagement?.toFixed(1) || '0.0'}%`],
      ['Reach', data?.analyticsData?.reach?.toLocaleString() || 'N/A', `${data?.analyticsData?.growth?.reach?.toFixed(1) || '0.0'}%`],
      ['Likes', data?.analyticsData?.likes?.toLocaleString() || 'N/A', `${data?.analyticsData?.growth?.likes?.toFixed(1) || '0.0'}%`],
      ['Comments', data?.analyticsData?.comments?.toLocaleString() || 'N/A', `${data?.analyticsData?.growth?.comments?.toFixed(1) || '0.0'}%`]
    ];

    // Table headers
    pdf.setFontSize(10);
    pdf.setFillColor(249, 250, 251);
    pdf.setTextColor(0, 0, 0);
    
    // Table data
    growthMetrics.forEach((row, index) => {
      const isHeader = index === 0;
      if (isHeader) {
        pdf.setFont('helvetica', 'bold');
        pdf.rect(margin, yPosition, pageWidth - 2 * margin, 8, 'F');
      } else {
        pdf.setFont('helvetica', 'normal');
      }

      pdf.text(row[0], margin + 2, yPosition + 6);
      pdf.text(row[1], margin + 60, yPosition + 6);
      pdf.text(row[2], margin + 120, yPosition + 6);

      yPosition += isHeader ? 8 : 6;
    });

    return yPosition + 20;
  };

  const generateFooter = (pdf: jsPDF, pageHeight: number, margin: number) => {
    const totalPages = pdf.internal.getNumberOfPages();
    
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Generated by Instagram GrowthHub Analytics • Page ${i} of ${totalPages}`,
        margin,
        pageHeight - 10
      );
    }
  };

  const generateExecutiveSummaryContent = (data: any): string => {
    if (!data?.analyticsData) {
      return 'No data available for analysis.';
    }

    const { followers, engagementRate, growth } = data.analyticsData;
    
    let summary = `This report analyzes your Instagram performance during the selected period. `;
    
    if (growth?.followers > 0) {
      summary += `Your account shows positive growth with a ${growth.followers.toFixed(1)}% increase in followers. `;
    } else if (growth?.followers < 0) {
      summary += `Your account experienced a ${Math.abs(growth.followers).toFixed(1)}% decline in followers. `;
    }
    
    if (growth?.engagement > 0) {
      summary += `Engagement rates improved by ${growth.engagement.toFixed(1)}%, indicating better audience interaction. `;
    } else if (growth?.engagement < 0) {
      summary += `Engagement rates decreased by ${Math.abs(growth.engagement).toFixed(1)}%, suggesting a need for content optimization. `;
    }
    
    summary += `The current engagement rate of ${engagementRate.toFixed(2)}% ${engagementRate >= 3 ? 'exceeds' : 'is below'} industry benchmarks. `;
    summary += `Focus on creating more engaging content to improve these metrics further.`;
    
    return summary;
  };

  const PreviewModal = () => {
    if (!showPreview) return null;

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-lg shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
          <div className="flex items-center justify-between p-4 border-b">
            <h3 className="text-lg font-semibold">PDF Report Preview</h3>
            <button
              onClick={() => setShowPreview(false)}
              className="text-gray-400 hover:text-gray-600"
            >
              ✕
            </button>
          </div>
          <div className="p-4 overflow-y-auto max-h-[calc(90vh-120px)]">
            <div 
              ref={reportRef}
              className="bg-white p-8 space-y-8"
              style={{ fontFamily: 'Arial, sans-serif' }}
            >
              {/* Cover Page Preview */}
              <div className="text-center border-b border-gray-200 pb-8">
                <h1 className="text-4xl font-bold text-purple-600 mb-2">{defaultOptions.title}</h1>
                <p className="text-xl text-gray-600 mb-4">{defaultOptions.subtitle}</p>
                <p className="text-gray-500">
                  Report Period: {data?.timeRange ? 
                    `${new Date(data.timeRange.start).toLocaleDateString()} - ${new Date(data.timeRange.end).toLocaleDateString()}` :
                    'Current Period'
                  }
                </p>
              </div>

              {/* Executive Summary Preview */}
              <div>
                <h2 className="text-2xl font-bold mb-4">Executive Summary</h2>
                <p className="text-gray-700 leading-relaxed">
                  {generateExecutiveSummaryContent(data)}
                </p>
              </div>

              {/* Key Metrics Preview */}
              <div>
                <h2 className="text-2xl font-bold mb-4">Key Performance Metrics</h2>
                <div className="grid grid-cols-2 gap-4">
                  {[
                    { label: 'Total Followers', value: data?.analyticsData?.followers?.toLocaleString() || 'N/A', color: 'text-blue-600' },
                    { label: 'Engagement Rate', value: `${data?.analyticsData?.engagementRate?.toFixed(2) || '0.00'}%`, color: 'text-green-600' },
                    { label: 'Total Reach', value: data?.analyticsData?.reach?.toLocaleString() || 'N/A', color: 'text-purple-600' },
                    { label: 'Total Likes', value: data?.analyticsData?.likes?.toLocaleString() || 'N/A', color: 'text-pink-600' }
                  ].map((metric) => (
                    <div key={metric.label} className="p-4 border border-gray-200 rounded-lg">
                      <p className="text-sm text-gray-600">{metric.label}</p>
                      <p className={`text-2xl font-bold ${metric.color}`}>{metric.value}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-4">
      {/* Preview Modal */}
      <PreviewModal />

      {/* Controls */}
      <div className="flex items-center gap-4">
        <button
          onClick={() => setShowPreview(true)}
          className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
        >
          <Eye className="h-4 w-4" />
          Preview
        </button>

        <button
          onClick={generatePDF}
          disabled={isGenerating}
          className="flex items-center gap-2 px-6 py-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-medium hover:shadow-lg transition-all disabled:opacity-50"
        >
          {isGenerating ? (
            <>
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
              Generating...
            </>
          ) : (
            <>
              <Download className="h-4 w-4" />
              Generate PDF
            </>
          )}
        </button>

        <button className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
          <Settings className="h-4 w-4" />
          Settings
        </button>
      </div>

      {/* Options Display */}
      <div className="text-sm text-gray-600 space-y-1">
        <p><strong>Template:</strong> {defaultOptions.template}</p>
        <p><strong>Include Charts:</strong> {defaultOptions.includeCharts ? 'Yes' : 'No'}</p>
        <p><strong>Include Analytics:</strong> {defaultOptions.includeAnalytics ? 'Yes' : 'No'}</p>
      </div>
    </div>
  );
}